### ISSUE TITLE
Docs say `output_fmt` but code says `format`

### ISSUE THREAD

**Issue by nlfiedler** [riverrun/pbkdf2_elixir#1]
The docs of the options param for `Pbkdf2.Base.hash_password()` says `output_fmt`, but the code expects `format`.

By the way, there are no tests for this parameter. When the docs are wrong or missing, the tests are a fallback for knowing how to use the API.

**Comment by riverrun** [comment]
I'll fix this later today. Thanks for pointing it out.

**Comment by riverrun** [comment]
Version 0.12.1 has a fix for this. I also added a test for default format and django format.
