### ISSUE TITLE
crypto:hmac is being removed in Erlang 24

### ISSUE THREAD

**Issue by isadon** [riverrun/pbkdf2_elixir#12]
Erlang 24 which is being released in a few months is removing crypto:hmac which this project uses. This project should update to use the new crypto api so projects depending on _it_ don't fail to build. Here is the notes from Erlang 24 http://erlang.org/doc/general_info/scheduled_for_removal.html#otp-24

**Comment by riverrun** [comment]
Thanks for letting me know - it's really appreciated.

**Comment by riverrun** [comment]
Note to myself:

This is how plug_crypto handled this situation - https://github.com/elixir-plug/plug_crypto/pull/20/files

**Comment by emtudo** [comment]
Is it possible to make changes?

I'm using Erlang 24.0.rc-2

**Comment by riverrun** [comment]
Yes, I hope to get the changes pushed within the next couple of days.

**Comment by emtudo** [comment]
thanks!

**Comment by riverrun** [comment]
Updated and released version 1.4
