### ISSUE TITLE
sha1

### ISSUE THREAD

**Issue by smokinguns** [riverrun/pbkdf2_elixir#2]
Ran into an issue where you can only use sha256 or sha512 on the password hash. I'm locked into supporting a legacy app that is using sha1, I was able to modify to include in the get options
 :sha -> {:sha , opts[:length] || 16} //Rfc2898DeriveBytes
I'm sure there are reasons for not doing this, but again supporting a legacy app. There is not even much reason for the encryption, except in my case i need to decrypt. I also found myself reversing the hex format, as i I just needed the binary format and not the base 16 encoding. Would it be worth putting a pull request together or just continue with the forked code.

**Comment by riverrun** [comment]
Maybe you can Plug's [implementation of Pbkdf2](https://hexdocs.pm/plug/Plug.Crypto.KeyGenerator.html). It will produce binary output, and you can use sha1 with that, as in the following example:

```
Plug.Crypto.KeyGenerator.generate("", "saltsalt", digest: :sha)
```

**Comment by smokinguns** [comment]
I will take a look. It does seem promising.

**Comment by riverrun** [comment]
Thanks for raising the issue, though. I think I should update the README with this kind of information, as Plug's key_generator is often the better choice - this library focuses just on password hashing.
